version: '3'
services:
  app:
    image: windingtherope/cdn:latest
    container_name: cdn
    restart: always
    ports:
      - 3030:3030
    working_dir: /app
    volumes:
      - ./:/app
      - type: bind
        source: ./folder
        target: /app/public
      
