services:
  app:
    image: windingtherope/cdn:latest
    container_name: cdn
    restart: always
    ports:
      - 3030:3030
    volumes:
      - type: bind
        source: /mnt/fcdn
        target: /app/public






